### ISSUE TITLE
The SVG image not behaving as expected

### ISSUE THREAD

**Issue by aditya-sarkar441** [Mangul-Lab-USC/Mangul-Lab-USC.github.io#16]
Website opening with Mangul Lab animated svg, but getting slided to its left. The svg is not behaving as I made it. The colours should appear at a later timestamp, but are coming instantly.

**Comment by Jdyn** [comment]
@aditya-sarkar441 It has been a while since this was opened, but I took a brief look at this. If I am interpreting it correctly, the intended effect is:
- The logo should not shift to the left near the end of the animation.
- The color should fade in over time

I removed the left logo translation and added a fading grayscale. 
[Here](https://i.imgur.com/hdcj1EU.gif) is a GIF of the new effect. I will open a PR if this is the intended effect. You can view the changes locally on the `intro-animation-fix` branch.

**Comment by aditya-sarkar441** [comment]
@Jdyn Yeah it looks good to me. You can make a pull request. I will merge it after consulting it with my PI (Dr Serghei Mangul). Thanks for your contribution!
